# Generated by Django 6.1.2 on 2026-10-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em andamento'), ('resolvido', 'Resolvido')], default='aberto', max_length=20),
        ),
    ]
