# Generated by Django 6.1.2 on 2026-10-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0002_chamado_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='solucao',
            field=models.TextField(blank=True, default=''),
        ),
    ]
